# Generated by Django 5.2.11 on 2026-03-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta_reports", "0081_auto_20260317_0457"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoints",
            name="label",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="historicalmissingogttnote",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="lastimprefill",
            name="label",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="missingogttnote",
            name="label",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
