# Generated by Django 5.2.11 on 2026-03-19 14:51
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        (
            "edc_qareports",
            "0025_remove_note_edc_qareports_note_report_model_subj_uniq_and_more",
        ),
        ("meta_reports", "0084_endpoints_fasted_hrs"),
    ]

    operations = []  # noqa: RUF012
