# Generated by Django 5.2.11 on 2026-03-19 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("meta_subject", "0245_alter_glucosefbg_options_and_more"),
        ("meta_reports", "0085_auto_20260319_1751"),
    ]

    operations = []
