# Generated by Django 5.2.11 on 2026-03-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("meta_reports", "0086_auto_20260320_0205"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="endpoints",
            name="fasted_hrs",
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
