# Generated by Django 5.2.11 on 2026-03-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta_reports", "0087_alter_endpoints_fasted_hrs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoints",
            name="visit_code",
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
