# Generated by Django 5.2.11 on 2026-04-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta_reports", "0088_alter_endpoints_visit_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoints",
            name="referral_date",
            field=models.DateField(null=True),
        ),
    ]
