# Generated by Django 5.2.11 on 2026-04-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta_reports", "0089_endpoints_referral_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoints",
            name="referral_id",
            field=models.UUIDField(null=True),
        ),
    ]
