# Generated by Django 5.2.11 on 2026-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_reports", "0092_auto_20260402_0100"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmissingogttnote",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="missingogttnote",
            name="label",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
