# Generated by Django 4.2.11 on 2024-06-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="unattendedthreeinrow",
            table="unattended_three_in_row_view",
        ),
    ]
