# Generated by Django 4.2.11 on 2024-06-06 19:16
from django.db import migrations

from meta_reports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ("meta_reports", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(read_unmanaged_model_sql("unattended_three_in_row.sql")),
        migrations.RunSQL(read_unmanaged_model_sql("unattended_three_in_row2.sql")),
        migrations.RunSQL(read_unmanaged_model_sql("unattended_two_in_row.sql")),
    ]
