# Generated by Django 4.2.11 on 2024-06-18 02:05

from django.db import migrations
from edc_qareports.utils import read_unmanaged_model_sql


class Migration(migrations.Migration):

    dependencies = [
        ("meta_reports", "0002_patienthistorymissingbaselinecd4_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            read_unmanaged_model_sql("unattended_three_in_row.sql", "meta_reports")
        ),
        migrations.RunSQL(
            read_unmanaged_model_sql("unattended_three_in_row2.sql", "meta_reports")
        ),
        migrations.RunSQL(
            read_unmanaged_model_sql("unattended_two_in_row.sql", "meta_reports")
        ),
        migrations.RunSQL(
            read_unmanaged_model_sql(
                "patient_history_missing_baseline_cd4.sql", "meta_reports"
            )
        ),
    ]
