# Generated by Django 5.2.6 on 2025-09-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_consent", "0033_historicalsubjectconsentspfq_subjectconsentspfq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectconsentspfq",
            name="site",
        ),
        migrations.DeleteModel(
            name="HistoricalSubjectConsentSpfq",
        ),
        migrations.DeleteModel(
            name="SubjectConsentSpfq",
        ),
    ]
