# Generated by Django 6.0.4 on 2026-04-20 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_consent",
            "0035_alter_historicalsubjectconsent_consent_definition_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="dm_comment",
            field=models.CharField(
                default="",
                editable=False,
                help_text="see also edc.data manager.",
                max_length=150,
                verbose_name="Data Management comment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="model_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="label_lower of this model class. Will be different if instance has been added/edited via a proxy model",
                max_length=50,
                verbose_name="model",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsent",
            name="sid",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Used for randomization against a prepared rando-list.",
                max_length=15,
                verbose_name="SID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="dm_comment",
            field=models.CharField(
                default="",
                editable=False,
                help_text="see also edc.data manager.",
                max_length=150,
                verbose_name="Data Management comment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="model_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="label_lower of this model class. Will be different if instance has been added/edited via a proxy model",
                max_length=50,
                verbose_name="model",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectconsentv1",
            name="sid",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Used for randomization against a prepared rando-list.",
                max_length=15,
                verbose_name="SID",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="dm_comment",
            field=models.CharField(
                default="",
                editable=False,
                help_text="see also edc.data manager.",
                max_length=150,
                verbose_name="Data Management comment",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="model_name",
            field=models.CharField(
                default="",
                editable=False,
                help_text="label_lower of this model class. Will be different if instance has been added/edited via a proxy model",
                max_length=50,
                verbose_name="model",
            ),
        ),
        migrations.AlterField(
            model_name="subjectconsent",
            name="sid",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Used for randomization against a prepared rando-list.",
                max_length=15,
                verbose_name="SID",
            ),
        ),
    ]
