# Generated by Django 6.0.8 on 2026-09-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_adverse_event", "0018_alter_aeactionclassification_options_and_more"),
        ("meta_ae", "0024_historicalaefinalclassification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aefinalclassification",
            name="conflict_resolved",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="Once yes, the classification above is yours and is not revised by the backfill. You will be asked again if the source reports change.",
                max_length=15,
                verbose_name="Have you reviewed this record and settled the classification above?",
            ),
        ),
        migrations.AddField(
            model_name="aefinalclassification",
            name="resolved_ae_classification",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_adverse_event.aeclassification",
                verbose_name="Original AE Classification, as reviewed",
            ),
        ),
        migrations.AddField(
            model_name="aefinalclassification",
            name="resolved_investigator_ae_classification",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="edc_adverse_event.aeclassification",
                verbose_name="Investigator AE Classification, as reviewed",
            ),
        ),
        migrations.AddField(
            model_name="aefinalclassification",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending: awaiting the AE TMG report"),
                    ("agreed", "Agreed: the original and TMG classifications agree"),
                    (
                        "requires_review",
                        "Requires review: the classifications do not agree",
                    ),
                ],
                default="PENDING",
                editable=False,
                help_text="Set from the source reports. Not editable.",
                max_length=25,
                verbose_name="Review status",
            ),
        ),
        migrations.AddField(
            model_name="historicalaefinalclassification",
            name="conflict_resolved",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="Once yes, the classification above is yours and is not revised by the backfill. You will be asked again if the source reports change.",
                max_length=15,
                verbose_name="Have you reviewed this record and settled the classification above?",
            ),
        ),
        migrations.AddField(
            model_name="historicalaefinalclassification",
            name="resolved_ae_classification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.aeclassification",
                verbose_name="Original AE Classification, as reviewed",
            ),
        ),
        migrations.AddField(
            model_name="historicalaefinalclassification",
            name="resolved_investigator_ae_classification",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_adverse_event.aeclassification",
                verbose_name="Investigator AE Classification, as reviewed",
            ),
        ),
        migrations.AddField(
            model_name="historicalaefinalclassification",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending: awaiting the AE TMG report"),
                    ("agreed", "Agreed: the original and TMG classifications agree"),
                    (
                        "requires_review",
                        "Requires review: the classifications do not agree",
                    ),
                ],
                default="PENDING",
                editable=False,
                help_text="Set from the source reports. Not editable.",
                max_length=25,
                verbose_name="Review status",
            ),
        ),
    ]
