# Generated by Django 6.0.8 on 2026-09-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_ae", "0026_convert_verified_to_review_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aefinalclassification",
            name="verified",
            field=models.BooleanField(default=False, help_text="Field retired"),
        ),
        migrations.AlterField(
            model_name="historicalaefinalclassification",
            name="verified",
            field=models.BooleanField(default=False, help_text="Field retired"),
        ),
    ]
