# Generated by Django 6.0.8 on 2026-09-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_ae",
            "0028_aefinalclassification_final_ae_classification_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aeinitial",
            name="ae_classification_comment",
            field=models.CharField(blank=True, max_length=250, default=""),
        ),
        migrations.AddField(
            model_name="aetmg",
            name="investigator_ae_classification_comment",
            field=models.CharField(blank=True, max_length=250,  default=""),
        ),
        migrations.AddField(
            model_name="historicalaeinitial",
            name="ae_classification_comment",
            field=models.CharField(blank=True, max_length=250,  default=""),
        ),
        migrations.AddField(
            model_name="historicalaetmg",
            name="investigator_ae_classification_comment",
            field=models.CharField(blank=True, max_length=250, default=""),
        ),
    ]
