tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "git-flow"
brew "jq"
brew "libmemcached"
brew "mysql", restart_service: true
brew "mysql-client"
brew "nginx"
brew "node"
brew "pandoc", link: false
brew "python@3.8"
brew "redis"
brew "tree"
brew "wget"
cask "wkhtmltopdf"
