# Generated by Django 3.0.6 on 2020-05-30 15:19

from django.db import migrations
import edc_visit_tracking.managers
import meta_subject.models.subject_visit


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0046_auto_20200530_1804"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="subjectvisit",
            managers=[
                ("on_site", meta_subject.models.subject_visit.CurrentSiteManager()),
                ("objects", edc_visit_tracking.managers.VisitModelManager()),
            ],
        ),
    ]
