# Generated by Django 3.2.4 on 2021-08-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """Added as a fake. Needed it to repair a test DB"""

    dependencies = [
        ("meta_subject", "0073_auto_20210809_0055"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="patienthistory",
        #     name="on_hypertension_treatment",
        #     field=models.CharField(
        #         choices=[("Yes", "Yes"), ("No", "No")],
        #         max_length=15,
        #         verbose_name="Is the patient on treatment for hypertension?",
        #     ),
        # ),
        # migrations.AddField(
        #     model_name="historicalpatienthistory",
        #     name="on_hypertension_treatment",
        #     field=models.CharField(
        #         choices=[("Yes", "Yes"), ("No", "No")],
        #         max_length=15,
        #         verbose_name="Is the patient on treatment for hypertension?",
        #     ),
        # ),
    ]
