# Generated by Django 4.2.11 on 2024-05-15 23:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0192_rename_glucose_quantifier_glucosefbg_fbg_quantifier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glucosefbg",
            name="fbg_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Glucose (FBG)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalglucosefbg",
            name="fbg_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(9999.99),
                ],
                verbose_name="Glucose (FBG)",
            ),
        ),
    ]
