# Generated by Django 4.2.11 on 2024-06-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0206_bloodresultsfbc_crf_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnattendedThreeInRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("subject_identifier", models.CharField(max_length=25)),
                ("site_id", models.CharField(max_length=25)),
                ("appt_datetime", models.DateTimeField()),
                ("first", models.CharField(max_length=25)),
                ("second", models.CharField(max_length=25)),
                ("third", models.CharField(max_length=25)),
                ("interval_days", models.IntegerField()),
                ("from_now_days", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Unattended: Three in a row",
                "verbose_name_plural": "Unattended: Three in a row",
                "db_table": "unattended_three_view",
                "managed": False,
            },
        ),
    ]
