from .spfg_admin import SpfqAdmin
from .spfg_refusal_admin import SpfqRefusalAdmin
from .spfq_for_withdrawal_admin import SpfqForWithdrawalAdmin
from .spfq_list_admin import SpfqListAdmin
from .subject_consent_spfq_admin import SubjectConsentSpfqAdmin
