# Generated by Django 6.0.8 on 2026-08-10 16:13

from django.db import migrations
from meta_prn.models import LossToFollowup


def update_number_consecutive_missed_visits_before_migrate(apps, schema_editor):
    LossToFollowup.objects.update(number_consecutive_missed_visits=None)


class Migration(migrations.Migration):

    dependencies = [
        ("meta_prn", "0071_alter_endofstudy_offstudy_reason_and_more"),
    ]

    operations = []
