# Generated by Django 6.0.8 on 2026-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meta_prn", "0072_auto_20260810_1913"),]

    operations = [
        migrations.AlterField(
            model_name="historicallosstofollowup",
            name="number_consecutive_missed_visits",
            field=models.IntegerField(
                null=True, verbose_name="Number of consecutive visits missed"
            ),
        ),
        migrations.AlterField(
            model_name="losstofollowup",
            name="number_consecutive_missed_visits",
            field=models.IntegerField(
                null=True, verbose_name="Number of consecutive visits missed"
            ),
        ),
    ]
