# Generated by Django 6.0.8 on 2026-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_prn",
            "0074_alter_historicallosstofollowup_number_consecutive_missed_visits_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dmreferral",
            name="not_referred_comment",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Please provide a brief reason why the participant was not referred",
            ),
        ),
        migrations.AddField(
            model_name="dmreferral",
            name="referred",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was the participant referred",
            ),
        ),
        migrations.AddField(
            model_name="historicaldmreferral",
            name="not_referred_comment",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Please provide a brief reason why the participant was not referred",
            ),
        ),
        migrations.AddField(
            model_name="historicaldmreferral",
            name="referred",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                max_length=15,
                verbose_name="Was the participant referred",
            ),
        ),
        migrations.AlterField(
            model_name="dmreferral",
            name="referral_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of referral to diabetes clinic",
            ),
        ),
        migrations.AlterField(
            model_name="dmreferral",
            name="referral_note",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Please provide a brief history of the diabetes diagnosis that lead to this referral",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmreferral",
            name="referral_date",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Date of referral to diabetes clinic",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmreferral",
            name="referral_note",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Please provide a brief history of the diabetes diagnosis that lead to this referral",
            ),
        ),
    ]
