# Generated by Django 6.0.8 on 2026-08-24 18:12

import edc_model.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_prn", "0076_endofstudy_admin_withdrawal_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="endofstudy",
            name="last_contact_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of last contact, if applicable",
            ),
        ),
        migrations.AddField(
            model_name="historicalendofstudy",
            name="last_contact_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of last contact, if applicable",
            ),
        ),
    ]
