# Generated by Django 6.0.8 on 2026-09-30 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_lists",
            "0023_adminwithdrawalreasons_clinicalwithdrawalreasons_and_more",
        ),
        ("meta_prn", "0079_endofstudy_admin_withdrawal_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endofstudy",
            old_name="admin_withdrawal_reason",
            new_name="admin_withdrawal_reason_name",
        ),
        migrations.RenameField(
            model_name="endofstudy",
            old_name="clinical_withdrawal_reason",
            new_name="clinical_withdrawal_reason_name",
        ),
        migrations.RenameField(
            model_name="historicalendofstudy",
            old_name="admin_withdrawal_reason",
            new_name="admin_withdrawal_reason_name",
        ),
        migrations.RenameField(
            model_name="historicalendofstudy",
            old_name="clinical_withdrawal_reason",
            new_name="clinical_withdrawal_reason_name",
        ),
    ]
