# Generated by Django 6.0.8 on 2026-09-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_prn", "0082_auto_20260930_2218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endofstudy",
            name="admin_withdrawal_reason_name",
            field=models.CharField(
                default="",
                max_length=25,
                verbose_name="If the patient was withdrawn for ADMINISTRATIVE reasons, please explain",
            ),
        ),
        migrations.AlterField(
            model_name="endofstudy",
            name="clinical_withdrawal_reason_name",
            field=models.CharField(
                default="",
                max_length=25,
                verbose_name="If the patient was withdrawn on CLINICAL grounds, please specify PRIMARY reason",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="admin_withdrawal_reason_name",
            field=models.CharField(
                default="",
                max_length=25,
                verbose_name="If the patient was withdrawn for ADMINISTRATIVE reasons, please explain",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="clinical_withdrawal_reason_name",
            field=models.CharField(
                default="",
                max_length=25,
                verbose_name="If the patient was withdrawn on CLINICAL grounds, please specify PRIMARY reason",
            ),
        ),
    ]
