# Generated by Django 6.0.8 on 2026-10-01 00:15

import django.db.models.deletion
import edc_model.validators.date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_lists",
            "0023_adminwithdrawalreasons_clinicalwithdrawalreasons_and_more",
        ),
        ("meta_prn", "0085_auto_20260930_2326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endofstudy",
            name="consent_withdrawal_inperson",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did the subject withdraw consent in-person",
            ),
        ),
        migrations.AlterField(
            model_name="endofstudy",
            name="consent_withdrawal_reason",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="meta_lists.consentwithdrawalreasons",
                verbose_name="Specify the PRIMARY reason the patient withdrew consent",
            ),
        ),
        migrations.AlterField(
            model_name="endofstudy",
            name="last_contact_date",
            field=models.DateField(
                blank=True,
                help_text="If provided, must be AFTER the date patient was last seen.",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of last contact, if applicable",
            ),
        ),
        migrations.AlterField(
            model_name="endofstudy",
            name="offstudy_reason",
            field=models.ForeignKey(
                limit_choices_to={
                    "name__in": [
                        "completed_followup",
                        "completed_followup_lt_36",
                        "completed_followup_lt_48",
                        "completed_followup_48",
                        "diabetes",
                        "delivery",
                        "pregnancy",
                        "clinical_withdrawal",
                        "dead",
                        "LTFU",
                        "toxicity",
                        "transferred",
                        "consent_withdrawal",
                        "late_exclusion",
                        "administrative_withdrawal",
                        "OTHER",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="meta_lists.offstudyreasons",
                verbose_name="Reason patient was terminated from the study",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="consent_withdrawal_inperson",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                max_length=15,
                verbose_name="Did the subject withdraw consent in-person",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="consent_withdrawal_reason",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="meta_lists.consentwithdrawalreasons",
                verbose_name="Specify the PRIMARY reason the patient withdrew consent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="last_contact_date",
            field=models.DateField(
                blank=True,
                help_text="If provided, must be AFTER the date patient was last seen.",
                null=True,
                validators=[edc_model.validators.date.date_not_future],
                verbose_name="Date of last contact, if applicable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalendofstudy",
            name="offstudy_reason",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                limit_choices_to={
                    "name__in": [
                        "completed_followup",
                        "completed_followup_lt_36",
                        "completed_followup_lt_48",
                        "completed_followup_48",
                        "diabetes",
                        "delivery",
                        "pregnancy",
                        "clinical_withdrawal",
                        "dead",
                        "LTFU",
                        "toxicity",
                        "transferred",
                        "consent_withdrawal",
                        "late_exclusion",
                        "administrative_withdrawal",
                        "OTHER",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="meta_lists.offstudyreasons",
                verbose_name="Reason patient was terminated from the study",
            ),
        ),
    ]
