# Generated by Django 6.0.8 on 2026-10-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_prn", "0087_auto_20261001_0347"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endofstudy",
            old_name="admin_withdrawal_reason_name",
            new_name="admin_withdrawal_reason_xxx",
        ),
        migrations.RenameField(
            model_name="endofstudy",
            old_name="clinical_withdrawal_reason_name",
            new_name="clinical_withdrawal_reason_xxx",
        ),
        migrations.RenameField(
            model_name="historicalendofstudy",
            old_name="admin_withdrawal_reason_name",
            new_name="admin_withdrawal_reason_xxx",
        ),
        migrations.RenameField(
            model_name="historicalendofstudy",
            old_name="clinical_withdrawal_reason_name",
            new_name="clinical_withdrawal_reason_xxx",
        ),
    ]
