# Generated by Django 3.2.11 on 2022-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_prn', '0017_auto_20220307_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthoutcomes',
            name='maternal_identifier',
            field=models.CharField(max_length=50),
        ),
    ]
