# Generated by Django 3.2.11 on 2022-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_prn', '0019_auto_20220307_2015'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delivery',
            unique_together={('subject_identifier', 'delivery_datetime')},
        ),
    ]
