from clinicedc_constants import UNKNOWN
from edc_transfer.constants import TRANSFERRED

from .constants import (
    CAREGIVING,
    CHANGED_CLINIC,
    DEATH,
    ERROR,
    FAMILY_EMERGENCY,
    ILLNESS,
    LACK_OF_TRANSPORT,
    SIDE_EFFECTS_IMP,
    TRAVELLING,
    UNABLE_TO_CONTACT,
    UNWILLING_TO_PARTICIPATE,
    UNWILLNG_IMP,
    WITHDREW_CONSENT,
    WORKING_SCHOOLING,
)

reason_categories = {
    "AWAY TAKING CARE OF HER SICK CHILD": CAREGIVING,
    "AWAY TAKING CARE OF HER SICK MOTHER": CAREGIVING,
    "AWAY TAKING CARE OF HER SICK RELATI": CAREGIVING,
    "AWAY TRAVELLING": TRAVELLING,
    "Attending other clinic at MNH": CHANGED_CLINIC,
    "Attending shamba in Rufiji": WORKING_SCHOOLING,
    "Away taking care of her sick relati": CAREGIVING,
    "Away taking care of his sick relati": CAREGIVING,
    "Away traveling": TRAVELLING,
    "Away travelled": TRAVELLING,
    "Away travelling": TRAVELLING,
    "Away travelling taking care of her": CAREGIVING,
    "Away travelling taking care of his": CAREGIVING,
    "Away travelling to singida": TRAVELLING,
    "Bussy work schedule": WORKING_SCHOOLING,
    "Busy schedule at work": WORKING_SCHOOLING,
    "Busy with tight schedule": WORKING_SCHOOLING,
    "Busy with tight timetable": WORKING_SCHOOLING,
    "Busy with work.": WORKING_SCHOOLING,
    "Busy work schedule": WORKING_SCHOOLING,
    "Can not continue with clinic": UNWILLING_TO_PARTICIPATE,
    "Can not walk due to fracture": ILLNESS,
    "Can't tolerate IMP": SIDE_EFFECTS_IMP,
    "Can't tolerate Imp": SIDE_EFFECTS_IMP,
    "Can't tolerate JMP": SIDE_EFFECTS_IMP,
    "Can't tolerate imp,": SIDE_EFFECTS_IMP,
    "Chaos": UNKNOWN,
    "Complains on side effects of IMP": SIDE_EFFECTS_IMP,
    "Consent withdraw": WITHDREW_CONSENT,
    "Don't like to take pills": UNWILLNG_IMP,
    "Don't want to continue taking IMP": UNWILLNG_IMP,
    "Don't want to continue with IMP": UNWILLNG_IMP,
    "Drugs make her unwell": SIDE_EFFECTS_IMP,
    "Family emergency": FAMILY_EMERGENCY,
    "Feeling unwell when she take drugs": SIDE_EFFECTS_IMP,
    "Forgot can't remember": UNKNOWN,
    "GOT FRACTURE, was sick": ILLNESS,
    "Got emergency but promised to come": FAMILY_EMERGENCY,
    "Had family conflict": FAMILY_EMERGENCY,
    "Has moved to Zanzibar for a while": TRANSFERRED,
    "Hasn't attended": UNKNOWN,
    "Her mother was sick": CAREGIVING,
    "I dont like to take pills": UNWILLNG_IMP,
    "I moved to a different residence": TRANSFERRED,
    "LOSS TO FOLLOW UP": "LTFU",
    "My child was sick": CAREGIVING,
    "No reason given": UNKNOWN,
    "Not ready to continue with IMP": UNWILLNG_IMP,
    "Not willing": UNWILLING_TO_PARTICIPATE,
    "Not willing to continue with IMP": UNWILLNG_IMP,
    "Not willing to participate": UNWILLING_TO_PARTICIPATE,
    "Now transfered, living in Tanga": TRANSFERRED,
    "Participant opted out": WITHDREW_CONSENT,
    "Participant withdrew consent": WITHDREW_CONSENT,
    "Participant withdrew from the study": WITHDREW_CONSENT,
    "Patient didn't attend clinic": UNKNOWN,
    "Patient has travelled": TRAVELLING,
    "Patient is away traveled": TRAVELLING,
    "Patient is away travelled": TRAVELLING,
    "Patient is not reachable": UNABLE_TO_CONTACT,
    "Patient is not reachbale": UNABLE_TO_CONTACT,
    "Patient is not rechable": UNABLE_TO_CONTACT,
    "Patient not ready": UNWILLING_TO_PARTICIPATE,
    "Patient promised to come": UNKNOWN,
    "Patient said can't tolerate imp": SIDE_EFFECTS_IMP,
    "Patient travelled": TRAVELLING,
    "Patient travelled To Zanzibar": TRAVELLING,
    "Patient travelled away": TRAVELLING,
    "Patient travelled out of Dar": TRAVELLING,
    "Patient travelled to MTWARA": TRAVELLING,
    "Patient was away travelled": TRAVELLING,
    "Patient was busy": WORKING_SCHOOLING,
    "Patticipant is away travelled": TRAVELLING,
    "Planned to travel she collected fo": TRAVELLING,
    "Promised to come": UNKNOWN,
    "Reported sick": ILLNESS,
    "Reported sick travelled": ILLNESS,
    "STUDY WITHDRAW": WITHDREW_CONSENT,
    "She cannot continue with the clinic": UNWILLING_TO_PARTICIPATE,
    "She do not want to take pills": UNWILLNG_IMP,
    "She is not willing to continue": UNWILLING_TO_PARTICIPATE,
    "She is very busy": WORKING_SCHOOLING,
    "She wa attending shamba in Morogoro": WORKING_SCHOOLING,
    "She was bisy": WORKING_SCHOOLING,
    "Sick": ILLNESS,
    "Sometimes IMP make her sick": SIDE_EFFECTS_IMP,
    "Still not well but promised to come": ILLNESS,
    "Study withdraw due to side effects": SIDE_EFFECTS_IMP,
    "TAKING CARE OF HER SICK MOTHER": CAREGIVING,
    "TRANSERED OUT TO SINGIDA RRH": TRANSFERRED,
    "TRAVELLING OUTSIDE OF COUNTRY": TRAVELLING,
    "TRAVELLING OUTSIDE TO ZAMBIA": TRAVELLING,
    "TRAVELLING TO KISARAWE": TRAVELLING,
    "TRVELLING TO MOZAMBIQUE": TRAVELLING,
    "Taking care of her sick relati in b": CAREGIVING,
    "Taking care of her sick relative in": CAREGIVING,
    "Taking care of his sick Father": CAREGIVING,
    "Taking care of sick relative in buk": CAREGIVING,
    "Too many pills": UNWILLNG_IMP,
    "Transfere to another region": TRANSFERRED,
    "Transfered to Dodoma": TRANSFERRED,
    "Transfered to Kagera": TRANSFERRED,
    "Transfered to Lindi": TRANSFERRED,
    "Transfered to Morogoro": TRANSFERRED,
    "Transferred Out": TRANSFERRED,
    "Transferred out to Tumbi Hospital": TRANSFERRED,
    "Travelled away": TRAVELLING,
    "Travelled away, promised to come": TRAVELLING,
    "Travelled to Tanga": TRAVELLING,
    "Travelled to mbeya": TRAVELLING,
    "Uknown": UNKNOWN,
    "Unwell": ILLNESS,
    "Very busy": WORKING_SCHOOLING,
    "Very busy with tight schedules": WORKING_SCHOOLING,
    "Very busy, with tight timetable": WORKING_SCHOOLING,
    "Want to withdraw from study": WITHDREW_CONSENT,
    "Want to withdraw from the study": WITHDREW_CONSENT,
    "Wanted a little break for few month": WORKING_SCHOOLING,
    "Wants to withdraw from imp": UNWILLNG_IMP,
    "Was away travelled": TRAVELLING,
    "Was busy but promised to come": WORKING_SCHOOLING,
    "Was busy travelled": TRAVELLING,
    "Was busy with tight schedule": WORKING_SCHOOLING,
    "Was not feeling well": ILLNESS,
    "Was not reachable, currently on": UNKNOWN,
    "Was not willing to participate": UNWILLING_TO_PARTICIPATE,
    "Was unknown": UNKNOWN,
    "Wishes to withdraw consent": WITHDREW_CONSENT,
    "Wishes to withdraw consentient": WITHDREW_CONSENT,
    "Withdraw study IMP": UNWILLNG_IMP,
    "Withdrew consent": WITHDREW_CONSENT,
    "Work transfer": TRANSFERRED,
    "XXX": UNKNOWN,
    "busy": WORKING_SCHOOLING,
    "busy work schedule": WORKING_SCHOOLING,
    "busy,promised to attend": WORKING_SCHOOLING,
    "can not continue with the clinic": UNWILLING_TO_PARTICIPATE,
    "client requested to withdraw consen": WITHDREW_CONSENT,
    "death": DEATH,
    "drug side effects": SIDE_EFFECTS_IMP,
    "drugs make her sick": SIDE_EFFECTS_IMP,
    "drugs making him sick": SIDE_EFFECTS_IMP,
    "family concerns": FAMILY_EMERGENCY,
    "family emergency": FAMILY_EMERGENCY,
    "family problems": FAMILY_EMERGENCY,
    "feeling bad after IMP uptake": SIDE_EFFECTS_IMP,
    "feeling unwell after imp uptake": SIDE_EFFECTS_IMP,
    "for withdrawl": WITHDREW_CONSENT,
    "gluc tested normal in other clinic": CHANGED_CLINIC,
    "incorrect termination": ERROR,
    "moved to a different area": TRANSFERRED,
    "no reason,promising to come": UNKNOWN,
    "opt to go for prayers": WORKING_SCHOOLING,
    "opted out, was sick and died": DEATH,
    "participant died": DEATH,
    "participant lacked transport": LACK_OF_TRANSPORT,
    "patient was sick and travelled away": ILLNESS,
    "pill burden": UNWILLNG_IMP,
    "pills make her to feel sick": SIDE_EFFECTS_IMP,
    "pills make him to feel sick": SIDE_EFFECTS_IMP,
    "post op care": ILLNESS,
    "she moved to Mbeya region for work": TRANSFERRED,
    "she was away for campaign": WORKING_SCHOOLING,
    "she was not feeling well": ILLNESS,
    "taking care of her sick daughter": CAREGIVING,
    "taking care of his sick kids": CAREGIVING,
    "too busy to come to the Centre.": WORKING_SCHOOLING,
    "travelled away, daughter was sick": CAREGIVING,
    "travelling to PEMBA for work": TRAVELLING,
    "travelling to bukoba for family iss": FAMILY_EMERGENCY,
    "want to withdraw consent": WITHDREW_CONSENT,
    "wishes to withdraw consent": WITHDREW_CONSENT,
    "withdraw consent": WITHDREW_CONSENT,
    "works as a truck drive": WORKING_SCHOOLING,
}
