# Generated by Django 5.1.2 on 2024-10-31 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0008_rename_allocation_lotnumber_assignment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="label",
            name="lot_no",
        ),
        migrations.RemoveField(
            model_name="label",
            name="rx",
        ),
        migrations.RemoveField(
            model_name="labelbatch",
            name="lot_number",
        ),
        migrations.RemoveField(
            model_name="labelbatch",
            name="site",
        ),
        migrations.RemoveField(
            model_name="labelbatchbarcodes",
            name="label_batch",
        ),
        migrations.RemoveField(
            model_name="labeldata",
            name="label_batch",
        ),
        migrations.RemoveField(
            model_name="historicallabeldata",
            name="label_batch",
        ),
        migrations.RemoveField(
            model_name="lotnumber",
            name="medication",
        ),
        migrations.DeleteModel(
            name="HistoricalLabelBatch",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.DeleteModel(
            name="LabelBatchBarcodes",
        ),
        migrations.DeleteModel(
            name="LabelBatch",
        ),
        migrations.DeleteModel(
            name="LotNumber",
        ),
    ]
