# Generated by Django 5.1.2 on 2024-10-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0009_historicallabeldata_batch_labeldata_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabeldata",
            name="pills_per_bottle",
            field=models.IntegerField(default=128, null=True),
        ),
        migrations.AddField(
            model_name="labeldata",
            name="pills_per_bottle",
            field=models.IntegerField(default=128, null=True),
        ),
    ]
