# Generated by Django 5.1.2 on 2024-11-04 17:51

import edc_pharmacy.models.stock_request.stock_request
import edc_pharmacy.models.stock_request.stock_request_item
import edc_sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "edc_pharmacy",
            "0024_assignment_containerunits_historicalassignment_and_more",
        ),
        ("meta_pharmacy", "0009_remove_label_lot_no_remove_label_rx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRequest",
            fields=[],
            options={
                "verbose_name": "Stock request",
                "verbose_name_plural": "Stock requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_pharmacy.stockrequest",),
            managers=[
                ("objects", edc_pharmacy.models.stock_request.stock_request.Manager()),
                ("on_site", edc_sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name="StockRequestItem",
            fields=[],
            options={
                "verbose_name": "Stock Request item",
                "verbose_name_plural": "Stock Request items",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_pharmacy.stockrequestitem",),
            managers=[
                (
                    "objects",
                    edc_pharmacy.models.stock_request.stock_request_item.Manager(),
                ),
            ],
        ),
    ]
