# Generated by Django 5.1.2 on 2024-11-09 21:53

import django.db.models.deletion
import edc_pharmacy.models.stock.stock_request
import edc_pharmacy.models.stock.stock_request_item
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edc_pharmacy", "0035_allocation_edc_pharmac_modifie_93b5ae_idx_and_more"),
        ("meta_pharmacy", "0009_remove_label_lot_no_remove_label_rx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockRequest",
            fields=[],
            options={
                "verbose_name": "Stock request",
                "verbose_name_plural": "Stock requests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_pharmacy.stockrequest",),
            managers=[
                ("objects", edc_pharmacy.models.stock.stock_request.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="StockRequestItem",
            fields=[],
            options={
                "verbose_name": "Stock Request item",
                "verbose_name_plural": "Stock Request items",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("edc_pharmacy.stockrequestitem",),
            managers=[
                ("objects", edc_pharmacy.models.stock.stock_request_item.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="historicalrx",
            name="registered_subject",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="edc_pharmacy.registeredsubjectproxy",
                verbose_name="Subject Identifier",
            ),
        ),
    ]
