# Generated by Django 5.1.2 on 2024-10-14 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0011_rename_allocation_lotnumber_assignment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicallabelbatch",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Label Batch",
                "verbose_name_plural": "historical Label Batch",
            },
        ),
        migrations.AlterModelOptions(
            name="labelbatch",
            options={"verbose_name": "Label Batch", "verbose_name_plural": "Label Batch"},
        ),
        migrations.RemoveField(
            model_name="historicallabeldata",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="labeldata",
            name="batch",
        ),
        migrations.AddField(
            model_name="historicallabeldata",
            name="label_batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="meta_pharmacy.labelbatch",
            ),
        ),
        migrations.AddField(
            model_name="labeldata",
            name="label_batch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="meta_pharmacy.labelbatch",
            ),
            preserve_default=False,
        ),
    ]
