# Generated by Django 5.1.2 on 2024-10-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0013_historicallabelbatch_barcodes_labelbatch_barcodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabelbatch",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="labelbatch",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=15
            ),
        ),
    ]
