# Generated by Django 5.1.2 on 2024-10-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0014_historicallabelbatch_status_labelbatch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallabelbatch",
            name="bottle_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="labelbatch",
            name="bottle_count",
            field=models.IntegerField(default=0),
        ),
    ]
