# Generated by Django 5.1.2 on 2024-10-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_pharmacy", "0015_historicallabelbatch_bottle_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallabelbatch",
            name="bottle_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="labelbatch",
            name="bottle_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
