APPT = "appt"
APPT_OTHER = "other_routine_appt"
DECREASED = "decreased"
PRESENT_REINFORCEMENT = "present_reinforcement"
REDUCED = "reduced"
FOLLOWUP_EXAMINATION_ACTION = "followup-examination-ae"
PRESENT_WITH_REINFORCEMENT = "present_with_reinforcement"
LOW_EGFR_ACTION = "low-egfr"
