# Generated by Django 5.1.2 on 2024-11-18 02:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0214_historicalstudymedication_stock_codes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalstudymedication",
            name="stock_codes",
            field=models.CharField(
                blank=True,
                help_text="Enter the medication bottle barcode or barcodes seperated by comma, no spaces",
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter one or more valid codes separated by comma",
                        regex="^([A-Z0-9]{6})(,[A-Z0-9]{6})*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studymedication",
            name="stock_codes",
            field=models.CharField(
                blank=True,
                help_text="Enter the medication bottle barcode or barcodes seperated by comma, no spaces",
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter one or more valid codes separated by comma",
                        regex="^([A-Z0-9]{6})(,[A-Z0-9]{6})*$",
                    )
                ],
            ),
        ),
    ]
