# Generated by Django 5.2.6 on 2025-09-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0233_historicalspfq_spfq"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spfq",
            name="site",
        ),
        migrations.RemoveField(
            model_name="spfq",
            name="subject_visit",
        ),
        migrations.DeleteModel(
            name="HistoricalSpfq",
        ),
        migrations.DeleteModel(
            name="Spfq",
        ),
    ]
