# Generated by Django 5.2.7 on 2025-10-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_subject",
            "0236_alter_historicalhivexitreview_other_current_arv_regimen_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalhivexitreview",
            name="singleton_field",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="auto updated for unique constraint",
                max_length=50,
                verbose_name="subject identifier",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hivexitreview",
            name="singleton_field",
            field=models.CharField(
                default="",
                editable=False,
                help_text="auto updated for unique constraint",
                max_length=50,
                unique=True,
                verbose_name="subject identifier",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="healtheconomicsupdate",
            name="singleton_field",
            field=models.CharField(
                default="",
                editable=False,
                help_text="auto updated for unique constraint",
                max_length=50,
                unique=True,
                verbose_name="subject identifier",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalhealtheconomicsupdate",
            name="singleton_field",
            field=models.CharField(
                db_index=True,
                default="",
                editable=False,
                help_text="auto updated for unique constraint",
                max_length=50,
                verbose_name="subject identifier",
            ),
            preserve_default=False,
        ),
    ]
