# Generated by Django 6.0.4 on 2026-05-07 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0246_auto_20260327_2009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmfollowup",
            name="last_missed_pill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("today", "today"),
                    ("yesterday", "yesterday"),
                    ("earlier_this_week", "earlier this week"),
                    ("last_week", "last week"),
                    ("lt_month_ago", "less than a month ago"),
                    ("gt_month_ago", "more than a month ago"),
                    ("NEVER", "have never missed taking my study pills"),
                ],
                default="",
                max_length=25,
                verbose_name="When was the last time you missed taking your pills?",
            ),
        ),
        migrations.AlterField(
            model_name="dmfollowup",
            name="visual_score_confirmed",
            field=models.IntegerField(
                blank=True,
                help_text="%",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Interviewer: please transcribe the score indicated from above.",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmfollowup",
            name="last_missed_pill",
            field=models.CharField(
                blank=True,
                choices=[
                    ("today", "today"),
                    ("yesterday", "yesterday"),
                    ("earlier_this_week", "earlier this week"),
                    ("last_week", "last week"),
                    ("lt_month_ago", "less than a month ago"),
                    ("gt_month_ago", "more than a month ago"),
                    ("NEVER", "have never missed taking my study pills"),
                ],
                default="",
                max_length=25,
                verbose_name="When was the last time you missed taking your pills?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldmfollowup",
            name="visual_score_confirmed",
            field=models.IntegerField(
                blank=True,
                help_text="%",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Interviewer: please transcribe the score indicated from above.",
            ),
        ),
    ]
