# Generated by Django 6.0.4 on 2026-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0248_historicalsubjectrequisition_laboratory_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsubjectrequisition",
            name="clinic_verified",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectrequisition",
            name="clinic_verified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subjectrequisition",
            name="clinic_verified",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("not_evaluated", "Not evaluated"),
                ],
                default="not_evaluated",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="subjectrequisition",
            name="clinic_verified_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
