# Generated by Django 6.0.8 on 2026-08-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meta_subject",
            "0252_rename_info_not_available_reason_delivery_report_not_available_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="report_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If NO, please explain below",
                max_length=5,
                verbose_name="Were you able to obtain a report on the delivery?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="report_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                default="N/A",
                help_text="If NO, please explain below",
                max_length=5,
                verbose_name="Were you able to obtain a report on the delivery?",
            ),
        ),
    ]
