# Generated by Django 6.0.8 on 2026-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0253_alter_delivery_report_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_time_estimated",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                verbose_name="Is the delivery TIME estimated?",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="gm_treated",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Was the participant treated for gestational diabetes?",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="report_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                help_text="If NO, please explain below",
                max_length=15,
                verbose_name="Were you able to obtain a report on the delivery?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="delivery_time_estimated",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                verbose_name="Is the delivery TIME estimated?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="gm_treated",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("unknown", "Unknown"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=15,
                verbose_name="Was the participant treated for gestational diabetes?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="report_available",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                default="Yes",
                help_text="If NO, please explain below",
                max_length=15,
                verbose_name="Were you able to obtain a report on the delivery?",
            ),
        ),
    ]
