# Generated by Django 6.0.8 on 2026-08-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_subject", "0254_alter_delivery_delivery_time_estimated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="delivery_location",
            field=models.CharField(
                choices=[
                    ("home", "At home"),
                    ("hospital_clinic", "Hospital / Clinic"),
                    ("unknown", "Unknown"),
                    ("OTHER", "Other location, specify"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Where did the delivery occur?",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="delivery_time_estimated",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                verbose_name="Is the date and time of delivery estimated?",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="info_source",
            field=models.CharField(
                choices=[
                    ("patient", "Study participant"),
                    ("hospital_clinic", "Hospital / Clinic"),
                    ("OTHER", "Other"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Who / what is the MAIN source of this information?",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="informant_relation",
            field=models.CharField(
                choices=[
                    ("husband_wife", "Husband/wife"),
                    ("Parent", "Parent"),
                    ("child", "Child"),
                    ("not_related", "Not related"),
                    ("unknown", "Unknown"),
                    ("OTHER", "Other"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Informants relationship to the participant?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="delivery_location",
            field=models.CharField(
                choices=[
                    ("home", "At home"),
                    ("hospital_clinic", "Hospital / Clinic"),
                    ("unknown", "Unknown"),
                    ("OTHER", "Other location, specify"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Where did the delivery occur?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="delivery_time_estimated",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No"), ("N/A", "Not applicable")],
                max_length=15,
                verbose_name="Is the date and time of delivery estimated?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="info_source",
            field=models.CharField(
                choices=[
                    ("patient", "Study participant"),
                    ("hospital_clinic", "Hospital / Clinic"),
                    ("OTHER", "Other"),
                    ("N/A", "Not applicable"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Who / what is the MAIN source of this information?",
            ),
        ),
        migrations.AlterField(
            model_name="historicaldelivery",
            name="informant_relation",
            field=models.CharField(
                choices=[
                    ("husband_wife", "Husband/wife"),
                    ("Parent", "Parent"),
                    ("child", "Child"),
                    ("not_related", "Not related"),
                    ("unknown", "Unknown"),
                    ("OTHER", "Other"),
                ],
                default="N/A",
                max_length=25,
                verbose_name="Informants relationship to the participant?",
            ),
        ),
    ]
