from .unattended_three_in_row2_admin import UnattendedThreeInRow2Admin
from .unattended_three_in_row_admin import UnattendedThreeInRowAdmin
from .unattended_two_in_row_admin import UnattendedTwoInRowAdmin
