# Generated by Django 5.2.7 on 2025-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_spfq", "0002_spfq_crf_status_spfq_crf_status_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="spfqlist",
            name="age_in_years",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
