# Generated by Django 5.2.11 on 2026-04-12 21:12

import django.contrib.sites.managers
import edc_consent.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meta_spfq", "0008_registeredsubjectproxy_spfqforwithdrawalrefusal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubjectConsentSpfqForWithdrawal",
            fields=[],
            options={
                "verbose_name": "Subject Consent SPFQ for Withdrawal",
                "verbose_name_plural": "Subject Consent SPFQ for Withdrawal",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("meta_spfq.subjectconsentspfq",),
            managers=[
                ("on_site", django.contrib.sites.managers.CurrentSiteManager()),
                ("objects", edc_consent.managers.ConsentObjectsManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="historicalspfqforwithdrawal",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical SPFQ for withdrawal",
                "verbose_name_plural": "historical SPFQ for withdrawals",
            },
        ),
        migrations.AlterModelOptions(
            name="spfqforwithdrawal",
            options={
                "default_manager_name": "objects",
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "export",
                    "import",
                ),
                "verbose_name": "SPFQ for withdrawal",
                "verbose_name_plural": "SPFQ for withdrawals",
            },
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="agreed_to_consented",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="assessment_score",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="consent_copy",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="consent_datetime",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="consent_reviewed",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="consent_signature",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="contact_attempted",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="contact_attempts_count",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="contact_attempts_explained",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="contact_made",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="historicalspfqforwithdrawal",
            name="study_questions",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="agreed_to_consented",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="assessment_score",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="consent_copy",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="consent_datetime",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="consent_reviewed",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="consent_signature",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="contact_attempted",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="contact_attempts_count",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="contact_attempts_explained",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="contact_made",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="reason",
        ),
        migrations.RemoveField(
            model_name="spfqforwithdrawal",
            name="study_questions",
        ),
        migrations.AddField(
            model_name="historicalspfqforwithdrawal",
            name="subject_identifier",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="spfqforwithdrawal",
            name="subject_identifier",
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
